export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_CATALOGS = "GET_CATALOGS"
export const GET_NEWS = 'GET_NEWS'
export const GET_NEW_WITH_ID = "GET_NEW_WITH_ID"
export const UPDATE_VIEWS = "UPDATE_VIEWS"
export const GET_PHOTO_GALLARY = "GET_PHOTO_GALLARY"